### ISSUE TITLE
Notes Created In Wrong Folder/No Template

### ISSUE THREAD

**Issue by brimwats** [charliecm/obsidian-upcoming#8]
Since the recent periodic notes update upcoming creates notes at vault root and doesn't apply the template.

I don't get any errors related to upcoming but here is what happens when I try to run it:

```
main.ts:131 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_handlers')
    at VimrcPlugin.getCursorActivityHandlers (main.ts:131:22)
    at VimrcPlugin.eval (main.ts:120:9)
    at step (tslib.es6.js:100:23)
    at Object.eval [as next] (tslib.es6.js:81:53)
    at eval (tslib.es6.js:74:71)
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70:12)
    at VimrcPlugin.updateSelectionEvent (main.ts:114:2)
    at VimrcPlugin.eval (main.ts:92:9)
    at step (tslib.es6.js:100:23)
main.ts:131 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_handlers')
    at VimrcPlugin.getCursorActivityHandlers (main.ts:131:22)
    at VimrcPlugin.eval (main.ts:120:9)
    at step (tslib.es6.js:100:23)
    at Object.eval [as next] (tslib.es6.js:81:53)
    at eval (tslib.es6.js:74:71)
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70:12)
    at VimrcPlugin.updateSelectionEvent (main.ts:114:2)
    at VimrcPlugin.eval (main.ts:96:9)
    at step (tslib.es6.js:100:23)
plugin:omnisearch:1 Uncaught (in promise) Error: MiniSearch: cannot remove document with ID 2022-11-15.md: it is not in the index
    at U.remove (plugin:omnisearch:1:9852)
    at VV.removeFromMinisearch (plugin:omnisearch:1:121119)
    at jV (plugin:omnisearch:8:1154155)
    at LV (plugin:omnisearch:8:1153526)
    at eval (plugin:omnisearch:8:1171669)
    at t.e.tryTrigger (app.js:1:1027924)
    at t.e.trigger (app.js:1:1027857)
    at t.trigger (app.js:1:1091465)
    at t.onChange (app.js:1:1082286)
    at e.trigger (app.js:1:1071812)
2
linkAttributes.ts:146 Uncaught TypeError: Cannot read properties of null (reading 'links')
    at eval (linkAttributes.ts:146:28)
    at t.iterateLeaves (app.js:1:1637661)
    at t.iterateLeaves (app.js:1:1637759)
    at t.iterateLeaves (app.js:1:1637759)
    at t.iterateRootLeaves (app.js:1:1637844)
    at updateVisibleLinks (linkAttributes.ts:131:19)
    at updateLinks (main.ts:30:4)
    at s (app.js:1:692224)
    at l (app.js:1:692330)
main.ts:131 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_handlers')
    at VimrcPlugin.getCursorActivityHandlers (main.ts:131:22)
    at VimrcPlugin.eval (main.ts:120:9)
    at step (tslib.es6.js:100:23)
    at Object.eval [as next] (tslib.es6.js:81:53)
    at eval (tslib.es6.js:74:71)
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70:12)
    at VimrcPlugin.updateSelectionEvent (main.ts:114:2)
    at VimrcPlugin.eval (main.ts:92:9)
    at step (tslib.es6.js:100:23)
main.ts:131 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_handlers')
    at VimrcPlugin.getCursorActivityHandlers (main.ts:131:22)
    at VimrcPlugin.eval (main.ts:120:9)
    at step (tslib.es6.js:100:23)
    at Object.eval [as next] (tslib.es6.js:81:53)
    at eval (tslib.es6.js:74:71)
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70:12)
    at VimrcPlugin.updateSelectionEvent (main.ts:114:2)
    at VimrcPlugin.eval (main.ts:96:9)
    at step (tslib.es6.js:100:23)
linkAttributes.ts:146 Uncaught TypeError: Cannot read properties of null (reading 'links')
    at eval (linkAttributes.ts:146:28)
    at t.iterateLeaves (app.js:1:1637661)
    at t.iterateLeaves (app.js:1:1637759)
    at t.iterateLeaves (app.js:1:1637759)
    at t.iterateRootLeaves (app.js:1:1637844)
    at updateVisibleLinks (linkAttributes.ts:131:19)
    at updateLinks (main.ts:30:4)
    at s (app.js:1:692224)
    at l (app.js:1:692330)
linkAttributes.ts:146 Uncaught TypeError: Cannot read properties of null (reading 'links')
    at eval (linkAttributes.ts:146:28)
    at t.iterateLeaves (app.js:1:1637661)
    at t.iterateLeaves (app.js:1:1637759)
    at t.iterateLeaves (app.js:1:1637759)
    at t.iterateRootLeaves (app.js:1:1637844)
    at updateVisibleLinks (linkAttributes.ts:131:19)
    at updateLinks (main.ts:30:4)
    at s (app.js:1:692224)
    at l (app.js:1:692330)
main.ts:131 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_handlers')
    at VimrcPlugin.getCursorActivityHandlers (main.ts:131:22)
    at VimrcPlugin.eval (main.ts:120:9)
    at step (tslib.es6.js:100:23)
    at Object.eval [as next] (tslib.es6.js:81:53)
    at eval (tslib.es6.js:74:71)
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70:12)
    at VimrcPlugin.updateSelectionEvent (main.ts:114:2)
    at VimrcPlugin.eval (main.ts:92:9)
    at step (tslib.es6.js:100:23)
plugin:obsidian-banners:13 Uncaught (in promise) TypeError: Cannot destructure property 'frontmatter' of 'this.metadata.getFileCache(...)' as it is null.
    at Ne.getBannerDataFromFile (plugin:obsidian-banners:13:831)
    at Mu.lintBannerSource (plugin:obsidian-banners:28:11227)
    at eval (plugin:obsidian-banners:28:9340)
    at t.e.tryTrigger (app.js:1:1027924)
    at t.e.trigger (app.js:1:1027857)
    at t.trigger (app.js:1:1648741)
    at t.activeLeafEvents (app.js:1:1634811)
    at s (app.js:1:692224)
    at l (app.js:1:692330)
main.ts:131 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_handlers')
    at VimrcPlugin.getCursorActivityHandlers (main.ts:131:22)
    at VimrcPlugin.eval (main.ts:120:9)
    at step (tslib.es6.js:100:23)
    at Object.eval [as next] (tslib.es6.js:81:53)
    at eval (tslib.es6.js:74:71)
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70:12)
    at VimrcPlugin.updateSelectionEvent (main.ts:114:2)
    at VimrcPlugin.eval (main.ts:96:9)
    at step (tslib.es6.js:100:23)
```

**Comment by charliecm** [comment]
@brimwats Thanks for reporting the issue. Can you tell me which version of Obsidian and Periodic Notes you're using?

Also, I'll be on vacation for a few weeks, so I'll look more into this when I'm back.

**Comment by brimwats** [comment]
> @brimwats Thanks for reporting the issue. Can you tell me which version of Obsidian and Periodic Notes you're using?
> 
> Also, I'll be on vacation for a few weeks, so I'll look more into this when I'm back.

No rush!

SYSTEM INFO:
	Obsidian version: v1.0.4
	Installer version: v1.0.4
	Operating system: Windows 10 Education 10.0.22000
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 21
	Restricted mode: off
	Plugins installed: 92
	Plugins enabled: 76
		1: Zotero Integration v2.2.31
		2: Word Sprint v0.2.3
		3: Vimrc Support v0.8.0
		4: Vim Yank Highlighter v1.1.4
		5: Vim Reading View Navigation v1.2.12
		6: Various Complements v7.3.0
		7: Upcoming v0.4.0
		8: Tweet to Markdown v2.11.2
		9: Text Generator v0.0.10
		10: Templater v1.16.0
		11: Tag Wrangler v0.5.5
		12: Table of Contents v0.1.3
		13: Table Generator v1.3.1
		14: Supercharged Links v0.9.3
		15: Style Settings v0.4.12
		16: Smarter Markdown Hotkeys v1.16.2
		17: Settings Search v1.2.0
		18: Advanced Tables v0.17.3
		19: Advanced URI v1.29.2
		20: Another Quick Switcher v7.2.2
		21: Banners v1.3.3
		22: Better Command Palette v0.14.0
		23: Breadcrumbs v3.6.4
		24: Code Editor Shortcuts v1.10.0
		25: Commander v0.3.0
		26: Contextual Typography v2.2.4
		27: Custom Frames v2.4.4
		28: CustomJS v1.0.12
		29: Dataview v0.5.51
		30: DB Folder v2.8.2
		31: Divide & Conquer v0.4.0
		32: Dynamic Highlights v0.3.1
		33: Dynamic Table of Contents v0.0.27
		34: Excalidraw v1.7.27
		35: File Explorer Note Count v1.2.0
		36: File Info Panel v1.2.5
		37: File path to URI v1.4.1
		38: Folder Note Core v1.3.5
		39: Footnote Shortcut v0.0.9
		40: Format Hotkeys v0.1.7
		41: Google Calendar v1.6.9
		42: Grandfather v1.0.1
		43: Hider v1.2.3
		44: Hotkey Helper v0.3.15
		45: AidenLx's Folder Note v0.16.4
		46: AidenLx's Folder Note - folderv component v1.0.0
		47: Sentence Navigator v1.2.0
		48: Reveal Active File Button v2.0.2
		49: Recent Files v1.3.3
		50: React Components v0.1.6
		51: QuickAdd v0.5.5
		52: Quick Explorer v0.2.3
		53: Plugin Update Tracker v1.1.1
		54: Plugin Changelogs v1.3.0
		55: Periodic Notes v1.0.0-beta.3
		56: Paste image rename v1.5.0
		57: Pane Relief v0.4.1
		58: Pandoc Plugin v0.4.1
		59: Outliner v4.1.1
		60: Open with v0.3.1
		61: Omnisearch v1.7.10
		62: Obsidian42 - BRAT v0.6.36
		63: Obsidian Charts v3.6.3
		64: Note Auto Creator v1.3.1
		65: Natural Language Dates v0.6.1
		66: Minimal Theme Settings v6.1.0
		67: Metadata Menu v0.3.5
		68: Media DB Plugin v0.4.1
		69: Longform v2.0.0
		70: Map View v2.2.0
		71: Local images v0.14.2
		72: List Modified v1.1.2
		73: Limelight v1.1.0
		74: Keyboard Analyzer v0.1.3
		75: Wikipedia v1.0.3
		76: Waypoint v1.3.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by charliecm** [comment]
@brimwats I'm revisiting this issue again. Are you still encountering it?

**Comment by brimwats** [comment]
I've stopped using daily notes and have switched to weekly! so I haven't seen this but haven't been using it :)
